const oracledb = require('oracledb');

// Configuración de conexión a Oracle
const config = {
    user: 'system',
    password: 'hola',
    connectString: 'localhost:1521/xe'
};

// Crear la tabla si no existe
async function createTable() {
    let connection;
    try {
        connection = await oracledb.getConnection(config);
        
        // Crear tabla leads si no existe
        await connection.execute(`
            BEGIN
                EXECUTE IMMEDIATE 'CREATE TABLE leads (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nombre VARCHAR2(100) NOT NULL,
                    email VARCHAR2(150) NOT NULL,
                    telefono VARCHAR2(20),
                    interes VARCHAR2(50),
                    mensaje CLOB,
                    fecha_registro DATE DEFAULT SYSDATE,
                    origen VARCHAR2(50)
                )';
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN
                        RAISE;
                    END IF;
            END;
        `);
        
        console.log('✅ Tabla leads creada/verificada');
        return true;
    } catch (error) {
        console.error('❌ Error con la tabla:', error);
        return false;
    } finally {
        if (connection) {
            await connection.close();
        }
    }
}

// Guardar lead en la base de datos
async function saveContact(data) {
    let connection;
    try {
        connection = await oracledb.getConnection(config);
        
        const result = await connection.execute(
            `INSERT INTO leads (nombre, email, telefono, interes, mensaje, origen) 
             VALUES (:nombre, :email, :telefono, :interes, :mensaje, :origen)`,
            {
                nombre: data.nombre,
                email: data.email,
                telefono: data.telefono || null,
                interes: data.interes,
                mensaje: data.mensaje || null,
                origen: 'formulario_contacto'
            },
            { autoCommit: true }
        );
        
        console.log('✅ Contacto guardado:', data.email);
        return { success: true, id: result.lastRowid };
    } catch (error) {
        console.error('❌ Error guardando contacto:', error);
        return { success: false, error: error.message };
    } finally {
        if (connection) {
            await connection.close();
        }
    }
}

module.exports = {
    createTable,
    saveContact
}; 